### PR TITLE
german locale

### PR DESCRIPTION
**Pull request by lucianojung**
- added german.dart as locale
- added german.dart as export in locale.dart

### CODE REVIEW

**Review by tejainece — APPROVED** [review]
LGTM

**Comment by tejainece** [comment]
I a surprised that we haven't got German translations for so long! Danke schön!

**Comment by lucianojung** [comment]
I was surprised too. No probs XD

**Comment by lucianojung** [comment]
If you want to support me you can star my repository showing examples of some flutter packages **including the date_format package** -> https://github.com/lucianojung/flutter_package_examples

**Pull request merged**
